title: Github Pages
author: William Pavei Antero
email: williamantero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Github pages
  
# social links
twitter_username: williamantero # DO NOT include the @ character, or else the build will fail!
github_username:  wantero # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
